import { describe, it, expect, beforeAll } from 'vitest';
import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

/**
 * Integration Tests: generate-prisma-bridges.js
 *
 * Verifica que el script de generación de CJS bridges para Prisma v7:
 * 1. Se ejecuta sin errores
 * 2. Genera archivos index.js en las rutas esperadas
 * 3. Los archivos generados contienen las exports esperadas (PrismaClient)
 * 4. Los regex patterns del bridge extraen correctamente datos de internal/class.ts
 *
 * Pre-requisito: prisma generate debe haberse ejecutado previamente
 * (los archivos internal/class.ts deben existir).
 */
describe('generate-prisma-bridges.js', () => {
  const apiRoot = path.resolve(__dirname, '..', '..');
  const scriptPath = path.join(apiRoot, 'scripts', 'generate-prisma-bridges.js');
  const mainBridgePath = path.join(apiRoot, 'prisma', 'main', 'generated', 'index.js');
  const tenantBridgePath = path.join(apiRoot, 'prisma', 'tenant', 'generated', 'index.js');
  const mainClassPath = path.join(apiRoot, 'prisma', 'main', 'generated', 'internal', 'class.ts');
  const tenantClassPath = path.join(
    apiRoot,
    'prisma',
    'tenant',
    'generated',
    'internal',
    'class.ts',
  );

  // --- Pre-condiciones ---

  it('debería tener el script en la ruta esperada', () => {
    expect(fs.existsSync(scriptPath)).toBe(true);
  });

  it('debería tener internal/class.ts para main (pre-requisito: prisma generate)', () => {
    expect(fs.existsSync(mainClassPath)).toBe(true);
  });

  it('debería tener internal/class.ts para tenant (pre-requisito: prisma generate)', () => {
    expect(fs.existsSync(tenantClassPath)).toBe(true);
  });

  // --- Ejecución del script ---

  describe('ejecución del script', () => {
    let stdout: string;

    beforeAll(() => {
      // Ejecutar el script desde la raíz del api/
      stdout = execSync(`node ${scriptPath}`, {
        cwd: apiRoot,
        encoding: 'utf8',
      });
    });

    it('debería ejecutarse sin errores', () => {
      expect(stdout).toContain('Prisma CJS bridges generated successfully');
    });

    it('debería reportar generación del bridge para main', () => {
      expect(stdout).toContain('Generated CJS bridge:');
      expect(stdout).toContain('main');
    });

    it('debería reportar generación del bridge para tenant', () => {
      expect(stdout).toContain('Generated CJS bridge:');
      expect(stdout).toContain('tenant');
    });
  });

  // --- Verificación del contenido generado ---

  describe('archivo bridge de main', () => {
    it('debería existir en prisma/main/generated/index.js', () => {
      expect(fs.existsSync(mainBridgePath)).toBe(true);
    });

    it('debería tener el header de auto-generación', () => {
      const content = fs.readFileSync(mainBridgePath, 'utf8');
      expect(content).toContain('AUTO-GENERATED by scripts/generate-prisma-bridges.js');
    });

    it('debería exportar PrismaClient', () => {
      const content = fs.readFileSync(mainBridgePath, 'utf8');
      expect(content).toContain('module.exports = { PrismaClient }');
    });

    it('debería importar @prisma/client/runtime/client', () => {
      const content = fs.readFileSync(mainBridgePath, 'utf8');
      expect(content).toContain("require('@prisma/client/runtime/client')");
    });

    it('debería leer internal/class.ts para extraer schema', () => {
      const content = fs.readFileSync(mainBridgePath, 'utf8');
      expect(content).toContain("path.join(__dirname, 'internal', 'class.ts')");
    });

    it('debería tener regex para inlineSchema', () => {
      const content = fs.readFileSync(mainBridgePath, 'utf8');
      expect(content).toContain('inlineSchemaMatch');
      expect(content).toContain('"inlineSchema"');
    });

    it('debería tener regex para runtimeDataModel', () => {
      const content = fs.readFileSync(mainBridgePath, 'utf8');
      expect(content).toContain('runtimeDataModelMatch');
      // En el regex del bridge, el punto se escapa como \., así que buscamos el texto real
      expect(content).toContain('runtimeDataModel');
    });

    it('debería configurar postgresql como activeProvider', () => {
      const content = fs.readFileSync(mainBridgePath, 'utf8');
      expect(content).toContain("activeProvider: 'postgresql'");
    });

    it('debería usar getPrismaClient del runtime', () => {
      const content = fs.readFileSync(mainBridgePath, 'utf8');
      expect(content).toContain('runtime.getPrismaClient(config)');
    });
  });

  describe('archivo bridge de tenant', () => {
    it('debería existir en prisma/tenant/generated/index.js', () => {
      expect(fs.existsSync(tenantBridgePath)).toBe(true);
    });

    it('debería tener el header de auto-generación', () => {
      const content = fs.readFileSync(tenantBridgePath, 'utf8');
      expect(content).toContain('AUTO-GENERATED by scripts/generate-prisma-bridges.js');
    });

    it('debería exportar PrismaClient', () => {
      const content = fs.readFileSync(tenantBridgePath, 'utf8');
      expect(content).toContain('module.exports = { PrismaClient }');
    });
  });

  // --- Verificación de los regex patterns (Bug 2 fix) ---

  describe('regex patterns del bridge template', () => {
    // Estos tests verifican que los patterns del bridge coinciden
    // con el formato real de internal/class.ts

    it('debería tener formato parseable en internal/class.ts de main', () => {
      const classContent = fs.readFileSync(mainClassPath, 'utf8');

      // Verificar que inlineSchema existe y es extraíble
      const inlineSchemaMatch = classContent.match(/"inlineSchema":\s*"((?:[^"\\]|\\.)*)"/);
      expect(inlineSchemaMatch).not.toBeNull();
      expect(inlineSchemaMatch![1].length).toBeGreaterThan(0);
    });

    it('debería tener runtimeDataModel parseable en internal/class.ts de main', () => {
      const classContent = fs.readFileSync(mainClassPath, 'utf8');

      const runtimeDataModelMatch = classContent.match(
        /config\.runtimeDataModel\s*=\s*JSON\.parse\("((?:[^"\\]|\\.)*)"/,
      );
      expect(runtimeDataModelMatch).not.toBeNull();

      // Verificar que el JSON es válido al parsearlo
      const parsed = JSON.parse(JSON.parse('"' + runtimeDataModelMatch![1] + '"'));
      expect(parsed).toHaveProperty('models');
    });

    it('debería tener formato parseable en internal/class.ts de tenant', () => {
      const classContent = fs.readFileSync(tenantClassPath, 'utf8');

      const inlineSchemaMatch = classContent.match(/"inlineSchema":\s*"((?:[^"\\]|\\.)*)"/);
      expect(inlineSchemaMatch).not.toBeNull();
    });
  });

  // --- Idempotencia ---

  describe('idempotencia', () => {
    it('debería generar el mismo contenido al ejecutar dos veces', () => {
      const contentBefore = fs.readFileSync(mainBridgePath, 'utf8');

      // Ejecutar el script otra vez
      execSync(`node ${scriptPath}`, {
        cwd: apiRoot,
        encoding: 'utf8',
      });

      const contentAfter = fs.readFileSync(mainBridgePath, 'utf8');
      expect(contentAfter).toBe(contentBefore);
    });
  });
});
