import { useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import { Button, Card, Divider, Group, List, Stack, Text, Title } from '@mantine/core';

import { formatDateLong } from '@/shared/utils/format-date';
import { formatMoney } from '@/shared/utils/format-money';

import { calculateAge } from '../utils/dni-validator';
import type { PersonalData, MemberType } from '../schemas/member-registration.schemas';

// === Tipos ===

interface RegistrationPlanInfo {
  feePlanId: string;
  name: string;
  amount: number;
}

interface ConfirmationStepProps {
  personalData: PersonalData;
  memberTypeId: string;
  memberTypes: MemberType[];
  /** Informacion del plan de alta activo (importe real). */
  registrationPlan?: RegistrationPlanInfo | null;
  onConfirm: () => Promise<void>;
  isSubmitting: boolean;
}

// === Componente ===

/**
 * Paso 3 del wizard de alta de socio.
 * Muestra un resumen de los datos del aspirante, el tipo de socio seleccionado,
 * los cargos que se generaran y un boton de confirmacion con proteccion contra doble clic.
 */
export function ConfirmationStep({
  personalData,
  memberTypeId,
  memberTypes,
  registrationPlan,
  onConfirm,
  isSubmitting,
}: ConfirmationStepProps) {
  const { t } = useTranslation('membership');

  // Tipo de socio seleccionado
  const selectedType = useMemo(
    () => memberTypes.find((t) => t.id === memberTypeId) ?? null,
    [memberTypes, memberTypeId],
  );

  // Edad calculada
  const age = useMemo(() => calculateAge(personalData.birthDate), [personalData.birthDate]);

  // Fecha de nacimiento formateada
  const birthDateFormatted = useMemo(
    () => formatDateLong(new Date(personalData.birthDate)),
    [personalData.birthDate],
  );

  // Fecha de hoy formateada
  const todayFormatted = useMemo(() => formatDateLong(new Date()), []);

  return (
    <Stack gap="lg">
      {/* Tarjeta de resumen del aspirante */}
      <Card shadow="sm" padding="lg" radius="md" withBorder>
        <Stack gap="md">
          <Title order={4}>{t('registration.confirmationStep.applicantData')}</Title>

          <SummaryRow
            label={t('registration.confirmationStep.fullName')}
            value={`${personalData.firstName} ${personalData.lastName}`}
          />
          <SummaryRow label={t('registration.confirmationStep.dniNie')} value={personalData.dni} />
          <SummaryRow
            label={t('registration.confirmationStep.birthDate')}
            value={`${birthDateFormatted} (${age} ${age === 1 ? t('registration.personalDataStep.ageYearSingular') : t('registration.personalDataStep.ageYearPlural')})`}
          />
          <SummaryRow label={t('registration.confirmationStep.email')} value={personalData.email} />
          {personalData.phone && (
            <SummaryRow
              label={t('registration.confirmationStep.phone')}
              value={personalData.phone}
            />
          )}
          {personalData.address && (
            <SummaryRow
              label={t('registration.confirmationStep.address')}
              value={personalData.address}
            />
          )}
          {personalData.postalCode && (
            <SummaryRow
              label={t('registration.confirmationStep.postalCode')}
              value={personalData.postalCode}
            />
          )}
          {personalData.city && (
            <SummaryRow label={t('registration.confirmationStep.city')} value={personalData.city} />
          )}

          <Divider />

          <SummaryRow
            label={t('registration.confirmationStep.memberType')}
            value={selectedType?.name ?? t('registration.confirmationStep.unknown')}
          />
          <SummaryRow
            label={t('registration.confirmationStep.registrationDate')}
            value={todayFormatted}
          />
        </Stack>
      </Card>

      {/* Seccion: Cargos a generar — Issue P1-3: importe real con formatMoney */}
      <Card shadow="sm" padding="lg" radius="md" withBorder>
        <Stack gap="md">
          <Title order={4}>{t('registration.confirmationStep.chargesToGenerate')}</Title>

          <Group justify="space-between" align="center">
            <Text size="sm">
              {registrationPlan
                ? registrationPlan.name
                : t('registration.confirmationStep.registrationFee')}
            </Text>
            <Text size="sm" fw={600}>
              {registrationPlan
                ? formatMoney(registrationPlan.amount)
                : t('registration.confirmationStep.feeAmountTbd')}
            </Text>
          </Group>

          <Text size="xs" c="dimmed">
            {t('registration.confirmationStep.feeAutoGenerated')}
          </Text>
        </Stack>
      </Card>

      {/* Seccion: Al confirmar */}
      <Card shadow="sm" padding="lg" radius="md" withBorder>
        <Stack gap="md">
          <Title order={4}>{t('registration.confirmationStep.onConfirmTitle')}</Title>

          <List size="sm" spacing="xs">
            <List.Item>{t('registration.confirmationStep.willCreateActive')}</List.Item>
            <List.Item>{t('registration.confirmationStep.willGenerateCharge')}</List.Item>
            <List.Item>{t('registration.confirmationStep.willAssignNumber')}</List.Item>
          </List>
        </Stack>
      </Card>

      {/* Boton de confirmacion */}
      <Group justify="flex-end">
        <Button
          color="brand"
          size="md"
          loading={isSubmitting}
          disabled={isSubmitting}
          onClick={onConfirm}
        >
          {t('registration.confirmationStep.confirmRegistration')}
        </Button>
      </Group>
    </Stack>
  );
}

// === Componentes auxiliares ===

interface SummaryRowProps {
  label: string;
  value: string;
}

/** Fila de resumen con etiqueta y valor. */
function SummaryRow({ label, value }: SummaryRowProps) {
  return (
    <Group justify="space-between" align="baseline">
      <Text size="sm" c="dimmed">
        {label}
      </Text>
      <Text size="sm" fw={500}>
        {value}
      </Text>
    </Group>
  );
}
